name: Package exe with PyInstaller - Windows

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set Release Version
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install fastapi
        pip install uvicorn[standard]
        pip install pywin32

    - name: Build
      run: |
        pyinstaller --clean --name altv-reconnect --onefile --icon=main.ico src/altv-reconnect.py

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.CI_SECRET }}
      with:
        name: "Release ${{ env.RELEASE_VERSION }}"
        tag_name: ${{ env.RELEASE_VERSION }}
        files: |
          dist/altv-reconnect.exe
